ARG PRODUCTION_IMAGE

FROM roeldev/php-composer:7.1-latest as composer

FROM ${PRODUCTION_IMAGE}
COPY --from=composer /usr/local/bin/composer /usr/local/bin/composer

ENV PATH=/root/.composer/vendor/bin:$PATH
VOLUME ["/yl/", "/root/.composer/"]
