FROM roeldev/casa-youless-logger:local

RUN set -x \
 && apk add \
        --no-cache \
            git

RUN set -x && install_composer.sh
RUN set -x && install_xdebug.sh

ENV COMPOSER_ALLOW_SUPERUSER=1 \
    PATH=/root/.composer/vendor/bin:/root/.symfony/bin:$PATH

VOLUME ["/app/", "/composer/cache/"]
