#!/usr/bin/with-contenv bash

if ${VERBOSE_INIT}
then
    echo
    echo "Starting cron..."
    echo "CRON_LOG_LEVEL: ${CRON_LOG_LEVEL}"
    echo "CRON_LOG_FILE:  ${CRON_LOG_FILE}"
    echo
else
    echo "Starting cron..."
fi

crond -f \
    -c /etc/crontabs/ \
    -l ${CRON_LOG_LEVEL} \
    -L "${CRON_LOG_FILE}"
