FROM roeldev/casa-youless:latest
ENV COMPOSER_ALLOW_SUPERUSER 1

COPY docker/install-composer.sh /tmp/
COPY docker/docker-entrypoint.sh /

RUN set -x && \
    # install composer
    sh /tmp/install-composer.sh && \
    # install xdebug dependencies
    apk add --no-cache --virtual phpize-deps \
        autoconf \
        g++ \
        make \
        && \
    # install xdebug
    pecl install xdebug && \
    docker-php-ext-enable xdebug && \
    # cleanup
    apk del phpize-deps && \
    rm -rf /tmp/*

ENV PATH /root/.composer/vendor/bin:$PATH
VOLUME ["/youless/", "/root/.composer/"]

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["supervisord", "-c", "/etc/supervisord.conf"]
