#!/bin/bash

CWD=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
PARENT_DIR=$( dirname "${CWD}" )

source ${PARENT_DIR}/.docker-build

# get description from github when not set
if [[ -z ${DESCRIPTION+x} ]]
then
    DESCRIPTION=$( \
        curl -s https://api.github.com/repos/${GITHUB_REPO} \
        | grep "description" \
        | cut -d : -f 2 \
        | awk '{$1=$1};1' \
        | cut -c 2- \
        | rev \
        | cut -c 3- \
        | rev
    )
fi

cmd="docker build \
    --label \"maintainer=${MAINTAINER}\" \
    --label \"description=${DESCRIPTION}\" \
    --label \"org.label-schema.name=${DOCKER_REPO}\" \
    --label \"org.label-schema.version=${DOCKER_TAG}\" \
    --label \"org.label-schema.build-date=${BUILD_DATE}\" \
    --label \"org.label-schema.vcs-ref=${GIT_REF}\" \
    --label \"org.label-schema.vcs-url=https://github.com/${GITHUB_REPO}\" \
    --label \"org.label-schema.schema-version=1.0\" \
    --file \"${PARENT_DIR}/Dockerfile\" \
    --tag \"${IMAGE_NAME}\" \
    \"$( realpath "${PARENT_DIR}/${BUILD_CONTEXT:-}" )\""

echo
echo ${cmd}
eval ${cmd}
echo
