#!/usr/bin/with-contenv bash

if [[ ! -f /yl/config/crontab ]]
then
    cp /yl/resources/default-crontab /yl/config/crontab
fi

if [[ ! -f /etc/crontabs/abc ]]
then
    cp /yl/config/crontab /etc/crontabs/abc
fi

mkdir -p "$( dirname "${CRON_LOG_FILE}" )"
chmod -R 0644 /etc/crontabs/
