#!/usr/bin/with-contenv bash

if [[ ! -f /yl/config/crontab ]]
then
    cp /yl/resources/default-crontab /yl/config/crontab
    ln -s /yl/config/crontab /etc/crontabs/youless-logger
    chmod 0644 \
        /etc/crontabs/youless-logger
        /yl/config/crontab
fi
