#!/usr/bin/with-contenv bash

if [[ ! -f /app/config/crontab ]]
then
    cp /app/resources/default-crontab /app/config/crontab
fi

if [[ ! -f /etc/crontabs/abc ]]
then
    cp /app/config/crontab /etc/crontabs/abc
fi

mkdir -p "$( dirname "${CRON_LOG_FILE}" )"
chmod -R 0644 /etc/crontabs/
